name: Actualizar Tasa BCV

on:
  schedule:
    # 9:00 AM hora de Venezuela (UTC-4) es 13:00 UTC
    - cron: '0 13 * * 1-5'
  workflow_dispatch:

# Añadimos permisos de escritura para que el bot pueda hacer el push
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar zona horaria Venezuela
        run: sudo timedatectl set-timezone America/Caracas

      - name: Descargar repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v5 # Actualizado a v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install pyBCV

      - name: Configurar Git y Sincronizar
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull origin main --rebase

      - name: Ejecutar script de grabación
        run: python history_bcv.py --auto

      - name: Guardar cambios en el JSON
        run: |
          git add historial_tasas.json
          # El commit solo se hace si hay cambios reales detectados por git
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-actualización tasa BCV: $(date +'%d-%m-%Y')" && git push origin main)
